Elcodi\Component\Rule\Entity\Abstracts\AbstractRule:
    type: entity
    repositoryClass: Elcodi\Component\Rule\Repository\AbstractRuleRepository
    inheritanceType: single_table
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        rule: Elcodi\Component\Rule\Entity\Rule
        rule_group: Elcodi\Component\Rule\Entity\RuleGroup
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        code:
            column: code
            type: string
            length: 255
            nullable: false
            unique: true
        enabled:
            column: enabled
            type: boolean
            nullable: false
