Elcodi\RuleBundle\Entity\Abstracts\AbstractRule:
    type: entity
    repositoryClass: Elcodi\RuleBundle\Repository\AbstractRuleRepository
    inheritanceType: single_table
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        rule: Elcodi\RuleBundle\Entity\Rule
        rule_group: Elcodi\RuleBundle\Entity\RuleGroup
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        code:
            column: code
            type: string
            length: 255
            nullable: false
            unique: true
        enabled:
            column: enabled
            type: boolean
            nullable: false
