Elcodi\RuleBundle\Entity\RuleGroup:
    type: entity
    repositoryClass: Elcodi\RuleBundle\Repository\RuleGroupRepository
    table: rule_group

    manyToMany:
        rules:
            targetEntity: Elcodi\RuleBundle\Entity\Abstracts\AbstractRule
            joinTable:
                name: rule_group_rule
                joinColumns:
                    rule_group_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    rule_id:
                        referencedColumnName: id
