parameters:

    #
    # Entities
    #
    elcodi.core.rule.entity.rule.class: Elcodi\Component\Rule\Entity\Rule

    #
    # Factories
    #
    elcodi.core.rule.factory.rule.class: Elcodi\Component\Rule\Factory\RuleFactory

    #
    # Managers
    #
    elcodi.core.rule.service.rule_manager.class: Elcodi\Component\Rule\Services\RuleManager

    #
    # External
    #
    elcodi.core.rule.service.expression_language.class: Symfony\Component\ExpressionLanguage\ExpressionLanguage

    #
    # Configurations
    #
    elcodi.core.rule.context_collector.class: Elcodi\Component\Rule\ExpressionLanguage\Context\ContextCollector
    elcodi.core.rule.expression_language.container_provider.class: Elcodi\Component\Rule\ExpressionLanguage\Provider\ContainerProvider
    elcodi.core.rule.expression_language.rule_provider.class: Elcodi\Component\Rule\ExpressionLanguage\Provider\RuleProvider
    elcodi.core.rule.expression_language.money_provider.class: Elcodi\Component\Rule\ExpressionLanguage\Provider\MoneyProvider
