parameters:

    #
    # Entities
    #
    elcodi.entity.rule.class: Elcodi\Component\Rule\Entity\Rule

    #
    # Factories
    #
    elcodi.factory.rule.class: Elcodi\Component\Rule\Factory\RuleFactory

    #
    # Managers
    #
    elcodi.manager.rule.class: Elcodi\Component\Rule\Services\RuleManager

    #
    # ExpressionLanguage
    #
    elcodi.expression_language.class: Symfony\Component\ExpressionLanguage\ExpressionLanguage
    elcodi.expression_language_context_collector.class: Elcodi\Component\Rule\ExpressionLanguage\Context\ContextCollector

    #
    # ExpressionLanguage providers
    #
    elcodi.expression_language_container_provider.class: Elcodi\Component\Rule\ExpressionLanguage\Provider\ContainerProvider
    elcodi.expression_language_rule_provider.class: Elcodi\Component\Rule\ExpressionLanguage\Provider\RuleProvider
