parameters:

    #
    # Test
    #
    elcodi.core.rule.test.parameter: value

    #
    # Entities
    #
    elcodi.core.rule.entity.abstract_rule.class: Elcodi\Component\Rule\Entity\Abstracts\AbstractRule
    elcodi.core.rule.entity.rule.class: Elcodi\Component\Rule\Entity\Rule
    elcodi.core.rule.entity.rule_group.class: Elcodi\Component\Rule\Entity\RuleGroup
    elcodi.core.rule.entity.expression.class: Elcodi\Component\Rule\Entity\Expression

    #
    # Repositories
    #
    elcodi.core.rule.repository.abstract_rule.class: Elcodi\Component\Rule\Repository\AbstractRuleRepository
    elcodi.core.rule.repository.rule.class: Elcodi\Component\Rule\Repository\RuleRepository
    elcodi.core.rule.repository.rule_group.class: Elcodi\Component\Rule\Repository\RuleGroupRepository
    elcodi.core.rule.repository.expression.class: Elcodi\Component\Rule\Repository\ExpressionRepository

    #
    # Factories
    #
    elcodi.core.rule.factory.rule.class: Elcodi\Component\Rule\Factory\RuleFactory
    elcodi.core.rule.factory.rule_group.class: Elcodi\Component\Rule\Factory\RuleGroupFactory
    elcodi.core.rule.factory.expression.class: Elcodi\Component\Rule\Factory\ExpressionFactory

    #
    # Managers
    #
    elcodi.core.rule.service.rule_manager.class: Elcodi\Component\Rule\Services\RuleManager

    #
    # External
    #
    elcodi.core.rule.service.expression_language.class: Symfony\Component\ExpressionLanguage\ExpressionLanguage

    #
    # Configurations
    #
    elcodi.core.rule.configuration.expression_language_collection.class: Elcodi\Component\Rule\Configuration\ExpressionLanguageConfigurationCollection
    elcodi.core.rule.configuration.context_collection.class: Elcodi\Component\Rule\Configuration\ContextConfigurationCollection
    elcodi.core.rule.configuration.expression_language.class: Elcodi\Component\Rule\Configuration\ExpressionLanguageConfiguration
    elcodi.core.rule.configuration.context.class: Elcodi\Component\Rule\Configuration\ContextConfiguration
    elcodi.core.rule.configuration.rule_manager.class: Elcodi\Component\Rule\Configuration\RuleManagerConfiguration
