services:
    elcodi.core.rule.context_collector:
        class: %elcodi.core.rule.context_collector.class%

    elcodi.core.rule.expression_language.container_provider:
        class: %elcodi.core.rule.expression_language.container_provider.class%
        arguments:
            - @service_container
        tags:
            - { name: elcodi.rule_configuration }

    elcodi.core.rule.expression_language.rule_provider:
        class: %elcodi.core.rule.expression_language.rule_provider.class%
        arguments:
            rule_repository: @elcodi.repository.rule
            rule_manager: @elcodi.rule_manager
        tags:
            - { name: elcodi.rule_configuration }
