services:

    #
    # ExpressionLanguage
    #
    elcodi.expression_language:
        class: %elcodi.expression_language.class%

    elcodi.expression_language_context_collector:
        class: %elcodi.expression_language_context_collector.class%

    #
    # ExpressionLanguage providers
    #
    elcodi.expression_language_container_provider:
        class: %elcodi.expression_language_container_provider.class%
        arguments:
            - @service_container
        tags:
            - { name: elcodi.rule_configuration }

    elcodi.expression_language_rule_provider:
        class: %elcodi.expression_language_rule_provider.class%
        arguments:
            - @elcodi.repository.rule
            - @elcodi.manager.rule
        tags:
            - { name: elcodi.rule_configuration }
