services:

    #
    # ExpressionLanguage
    #
    elcodi.core.rule.service.expression_language:
        class: %elcodi.core.rule.service.expression_language.class%

    elcodi.core.rule.context_collector:
        class: %elcodi.core.rule.context_collector.class%

    #
    # ExpressionLanguage providers
    #
    elcodi.core.rule.expression_language.container_provider:
        class: %elcodi.core.rule.expression_language.container_provider.class%
        arguments:
            - @service_container
        tags:
            - { name: elcodi.rule_configuration }

    elcodi.core.rule.expression_language.rule_provider:
        class: %elcodi.core.rule.expression_language.rule_provider.class%
        arguments:
            - @elcodi.repository.rule
            - @elcodi.rule_manager
        tags:
            - { name: elcodi.rule_configuration }
