services:

    #
    # Factories
    #

    #
    # Factory for entity rule
    #
    elcodi.core.rule.factory.rule:
        class: %elcodi.core.rule.factory.rule.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.rule.entity.rule.class%"]]

    elcodi.factory.rule:
        alias: elcodi.core.rule.factory.rule
