services:

    #
    # Factories
    #

    #
    # Factory for entity rule
    #
    elcodi.core.rule.factory.rule:
        class: %elcodi.core.rule.factory.rule.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.rule.entity.rule.class%"]]

    elcodi.factory.rule:
        alias: elcodi.core.rule.factory.rule

    #
    # Factory for entity rule_group
    #
    elcodi.core.rule.factory.rule_group:
        class: %elcodi.core.rule.factory.rule_group.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.rule.entity.rule_group.class%"]]

    elcodi.factory.rule_group:
        alias: elcodi.core.rule.factory.rule_group

    #
    # Factory for entity expression
    #
    elcodi.core.rule.factory.expression:
        class: %elcodi.core.rule.factory.expression.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.rule.entity.expression.class%"]]

    elcodi.factory.expression:
        alias: elcodi.core.rule.factory.expression

    #
    # Entity providers
    #

    #
    # Instance provider for entity rule
    #
    elcodi.core.rule.entity.rule.instance:
        class: %elcodi.core.rule.entity.rule.class%
        factory_service: elcodi.core.rule.factory.rule
        factory_method: create
        scope: prototype

    elcodi.entity.rule.instance:
        alias: elcodi.core.rule.entity.rule.instance

    #
    # Instance provider for entity rule_group
    #
    elcodi.core.rule.entity.rule_group.instance:
        class: %elcodi.core.rule.entity.rule_group.class%
        factory_service: elcodi.core.rule.factory.rule_group
        factory_method: create
        scope: prototype

    elcodi.entity.rule_group.instance:
        alias: elcodi.core.rule.entity.rule_group.instance

    #
    # Instance provider for entity expression
    #
    elcodi.core.rule.entity.expression.instance:
        class: %elcodi.core.rule.entity.expression.class%
        factory_service: elcodi.core.rule.factory.expression
        factory_method: create
        scope: prototype

    elcodi.entity.expression.instance:
        alias: elcodi.core.rule.entity.expression.instance
