services:

    #
    # factories
    #
    elcodi.core.rule.factory.rule:
        class: %elcodi.core.rule.factory.rule.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.rule.entity.rule.class%"]]

    elcodi.core.rule.factory.rule_group:
        class: %elcodi.core.rule.factory.rule_group.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.rule.entity.rule_group.class%"]]

    elcodi.core.rule.factory.expression:
        class: %elcodi.core.rule.factory.expression.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.rule.entity.expression.class%"]]

    #
    # Entity providers
    #
    elcodi.core.rule.entity.customer.instance:
        class: %elcodi.core.user.factory.customer.class%
        factory_service: elcodi.core.user.factory.customer
        factory_method: create