services:

    #
    # Factories
    #

    #
    # Factory for entity rule
    #
    elcodi.factory.rule:
        class: %elcodi.factory.rule.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.rule.class%"]]
