services:

    #
    # Provider specific for Currency Wrapper
    #
    elcodi.core.rule.expression_language.money_provider:
        class: %elcodi.core.rule.expression_language.money_provider.class%
        arguments:
            - @elcodi.currency_wrapper
        tags:
            - { name: elcodi.rule_configuration }
