services:

    #
    # Repositories
    #

    #
    # Repository for entity rule
    #
    elcodi.repository.rule:
        parent: elcodi.abstract_repository
        arguments: [ %elcodi.core.rule.entity.rule.class% ]
