services:

    #
    # Repositories
    #

    #
    # Repository for entity abstract rule
    #
    elcodi.repository.abstract_rule:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.rule.entity.abstract_rule.class%

    #
    # Repository for entity rule
    #
    elcodi.repository.rule:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.rule.entity.rule.class%

    #
    # Repository for entity rule_group
    #
    elcodi.repository.rule_group:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.rule.entity.rule_group.class%

    #
    # Repository for entity expression
    #
    elcodi.repository.expression:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.rule.entity.expression.class%
