services:

    #
    # Managers
    #
    elcodi.manager.rule:
        class: %elcodi.manager.rule.class%
        lazy: true
        arguments:
            expression_language: @elcodi.expression_language
            context_provider: @elcodi.expression_language_context_collector
