services:

    #
    # Managers
    #
    elcodi.rule_manager:
        class: %elcodi.rule_manager.class%
        lazy: true
        arguments:
            expression_language: @elcodi.expression_language
            context_provider: @elcodi.expression_language_context_collector
