services:

    #
    # Managers
    #
    elcodi.manager.rule:
        class: %elcodi.manager.rule.class%
        lazy: true
        arguments:
            - @elcodi.expression_language
            - @elcodi.expression_language_context_collector
